{
  "comments": [
    {
      "key": {
        "uuid": "c42537aa_82a88822",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 5110
      },
      "writtenOn": "2013-09-19T20:47:40Z",
      "side": 1,
      "message": "Can you elaborate this further? Aren\u0027t the exception already broken because we are throwing java objects instead of real js exceptions?",
      "revId": "48699b662dc8bd9843daf02def42e89fe9ed22f1",
      "serverId": "84fdd5b9-d3fc-3149-9ae9-e619898c4c46",
      "unresolved": false
    }
  ]
}